change code

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -7,7 +7,7 @@ workflows:
       app_store_connect: EPG LLC
     environment:
       vars:
-        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
+        XCODE_PROJECT: "ios/App/App.xcodeproj"
         XCODE_SCHEME: "App"
         APP_STORE_APP_ID: 6744694610
       node: 20.11.1
@@ -29,15 +29,16 @@ workflows:
       - name: Install npm dependencies for Ionic project
         script: |
           npm install
-      - name: Cocoapods installation
-        script: |
-          cd ios/App && pod install
       - name: Compile web code to dist folder
         script: |
           npm run build
       - name: Update dependencies and copy web assets to native project
         script: |
           npx cap sync
+      - name: Debug project file existence
+        script: |
+          echo "Checking for Xcode project file..."
+          ls -l $XCODE_PROJECT || echo "Xcode project file not found"
       - name: Debug provisioning profiles and certificates
         script: |
           echo "Listing provisioning profiles..."
@@ -53,10 +54,10 @@ workflows:
       - name: Debug bundle ID in Xcode project
         script: |
           echo "Checking bundle ID in Xcode project..."
-          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER
+          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | grep PRODUCT_BUNDLE_IDENTIFIER
       - name: Show build settings
         script: |
-          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings
+          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings
       - name: Increment build number
         script: |
           cd ios/App
@@ -80,7 +81,7 @@ workflows:
       - name: Build ipa for distribution
         script: |
           cd ios/App
-          xcodebuild -workspace "$XCODE_WORKSPACE" \
+          xcodebuild -project App.xcodeproj \
             -scheme "$XCODE_SCHEME" \
             -archivePath "build/App.xcarchive" \
             -configuration Release \
